sonr-io/beam-react-native

- App.tsx
> Fix not being able to render on browser

- App.tsx
- package.json
- src/_data/chats.tsx
- src/_data/users.tsx
- src/components/Chat/ChatItem.tsx
- src/lib/getTime.ts
- src/screens/Chat/ChatList.tsx
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/index.tsx
- src/screens/ChatList.tsx
- yarn.lock
https://www.pivotaltracker.com/story/show/181923909
> [Feature] chat screen polishing

- src/components/FAB.tsx
- src/components/GradientHeader.native.tsx
- src/components/GradientHeader.tsx
- src/screens/Chat/ChatList.tsx
- src/screens/Chat/ChatNew.tsx
- src/screens/Chat/index.tsx
- Not meant to be the final version. I just want to send it quickly and avoid conflicts 😃 
> Screen flow for "New chat"

- .husky/pre-commit
- package.json
- src/components/GradientHeader.tsx
- yarn.lock
added husky that will run lint-fix before commit 
> Added husky

- src/screens/Chat/ChatView.tsx
https://www.pivotaltracker.com/story/show/182039227
> [Feature] chat input grows on multiline inputs

- App.tsx
- package.json
- src/components/Avatar/Avatar.tsx
- src/components/Chat/ChatListItem.tsx
- src/components/GradientTop.tsx
- src/components/NewChatButton.tsx
- src/icons/User.tsx
- src/screens/Chat/ChatList.tsx
- src/screens/Chat/ChatView.tsx
- yarn.lock
- https://www.pivotaltracker.com/story/show/182056283
- partial implementation. includes the header + avatar icon
> ChatList v1 design: header + avatar icon

- App.tsx
- src/components/Chat/ChatItem.tsx
- src/components/MessageBubble.tsx
- src/screens/Chat/ChatView.tsx
- src/types/Chat.ts
- the goal with this component is to isolate the appearance of a message
> MessageBubble component

- @types/allTypes.d.ts
- src/screens/Chat/ChatView.tsx
> Fix declaration error on open graph parser

- src/_data/chats.tsx
- src/components/Chat/ChatItem.tsx
- src/components/ReplyBubble.tsx
- src/screens/Chat/ChatView.tsx
- src/types/Chat.ts
- Chat now displays a preview of messages that have been replied
- I've been calling it "parentMessage" but I'm not happy with that name. Please let me know if you have better ideas.
> Display replied message in chat

- src/screens/Chat/MessageMenu.tsx
- Changed a bit how the message shows on the message menu
- "Back"button is gone and now the background is clickable
I'll finish the rest of the elements soon, after I work on the replied messages UI for the ChatView
> [Partial] Minor updates on MessageMenu

- App.tsx
- src/_data/chats.tsx
- src/contexts/ChatContext.ts
- src/contexts/UserContext.ts
- src/screens/Chat/ChatList.tsx
- src/screens/Chat/ChatView.tsx
Add a link to the Pivotal ticket and a brief description of the changes included in this PR.
Describe impact, risks and mitigation if applicable.
- Impact: (Critical / High / Medium / Low)
- Critical: Architectural changes / big refactorings / changes that touches core parts that can impact service availability
- High: Changes to core features / UI changes that can block app usage
- Medium: UI changes that can block some actions but not the core features
- Low: Small UI changes on rarely used features (Most users wouldn't even notice)
- Mitigation: These changes are behind a beta-flag / This feature isn't publicly available yet /
Describe test steps to check if the changes are working properly and that it meets the ticket AC.
Is there any setup steps needed?
Is there unit tests to cover …
> Using context

- App.tsx
- src/_data/chats.tsx
- src/components/MessageBubble.tsx
- src/contexts/ChatContext.ts
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/MessageMenu.tsx
- src/screens/Chat/index.tsx
- src/types/Chat.ts
- reacting now saves it to message
- abbreviating when there are more than 3 reactions on the same message
- minor changes to the fake user session
> Connect reactions to fake chats

- App.tsx
- src/components/NewChatButton.tsx
- src/screens/Chat/ChatView.tsx
> [Feature] make background appear underneath bottom bar

- package.json
> Remove unused fonts

- App.tsx
- package.json
- src/contexts/MatrixClientContext.ts
- src/lib/matrix.ts
- src/screens/Login.tsx
- src/types/xmlhttp-request.d.ts
- yarn.lock
[#182224752](https://www.pivotaltracker.com/story/show/182224752)
> [Chore] add matrix SDK

- .github/workflows/checks.yml
- package.json
- src/lib/getFormattedDay.test.ts
- src/lib/normalizeUrl.test.ts
- yarn.lock
[#182223737](https://www.pivotaltracker.com/story/show/182223737)
`yarn test`
> [Chore] add test framework

- .gitignore
- README.md
- babel.config.js
- package.json
- src/screens/Login.tsx
- src/types/env.d.ts
- yarn.lock
[#182250464](https://www.pivotaltracker.com/story/show/182250464)
Create a `.env` file on the root folder with the test users formatted like this:
```
USERS='[ { "username": "UserA", "password": "..." }, { "username": "UserB", "password": "..." }, { "username": "UserC", "password": "..." } ]'
```
then open the app and you should see a button for each user on the login screen.
> [Feature] quick login with test users

- package.json
- src/components/Emojis/EmojiCategoryView.tsx
- yarn.lock
[#182215121](https://www.pivotaltracker.com/story/show/182215121)
Go to any message and open the emoji selector, no error should be thrown.
> [Chore] fix ScrollableTabView error

- App.tsx
- src/screens/Login.tsx
- Just added some styles to the temp login page
- nothin fancy
> Add some css to temp login

- App.tsx
- intl-collator.js
- src/lib/matrix.ts
- fixes for android to work with matrix-js-sdk
> [Chore] Stable staging

- @types/allTypes.d.ts
- package.json
- src/lib/splitMessageText.ts
- yarn.lock
> Use matchAll lib instead of string method (not available on Android)

- App.tsx
- src/lib/matrix.ts
- src/screens/Login.tsx
[#182225257](https://www.pivotaltracker.com/story/show/182225257)
Login with matrix user, then go to chat list screen and the chats should be there.
> [Feature] list of chats (Matrix)

- App.tsx
- src/contexts/ChatContext.ts
- src/contexts/UserContext.ts
- src/lib/matrix.ts
- src/screens/Chat/ChatView.tsx
- src/screens/Login.tsx
> [Feature] exchange messages

- src/lib/matrix.ts
- src/screens/Login.tsx
[#182225995](https://www.pivotaltracker.com/story/show/182225995)
After log in, all messages should appear on the chats.
> [Feature] show chat

- App.tsx
- src/components/Chat/ChatItem.tsx
- src/contexts/MatrixClientContext.ts
- src/lib/matrix.ts
- src/screens/Chat/MessageMenu.tsx
- src/screens/Login.tsx
[#182226189](https://www.pivotaltracker.com/story/show/182226189)
Go to any chat and reply to a message, it should appear as a reply on the other end.
> [Feature] reply to a message

- App.tsx
- src/components/Chat/ChatListItem.tsx
- src/components/StartNewChat.tsx
- src/lib/matrix.ts
- src/screens/Chat/NewChat.tsx
- src/screens/Login.tsx
- src/types/Chat.ts
- https://www.pivotaltracker.com/story/show/182226206
- only starts chat if user exists
- chats are joined automatically on login
- does not allow duplicate chats
- does not allow starting chat with self
> [Feature] Start a new chat

- App.tsx
- src/components/Chat/ChatItem.tsx
- src/contexts/MatrixClientContext.ts
- src/lib/matrix.ts
- src/screens/Chat/ForwardMenu.tsx
- src/screens/Chat/MessageMenu.tsx
- src/screens/Login.tsx
[#182226195](https://www.pivotaltracker.com/story/show/182226195)
Go to any chat, forward a message, and it should appear on the other device marked as "Forwarded from ...". Also, when loading the messages after sign in, it should appear as forwarded.
> [Feature] forward message

- App.tsx
- package.json
- src/components/Emojis/EmojiItem.tsx
- src/components/Emojis/EmojiSelector.tsx
- src/contexts/ChatContext.ts
- src/lib/emoji.ts
- src/lib/matrix.ts
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/ForwardMenu.tsx
- src/screens/Chat/MessageMenu.tsx
- src/screens/Login.tsx
- yarn.lock
[#182226191](https://www.pivotaltracker.com/story/show/182226191)
Go to any chat, react to a message and it should appear on the other client. Also, after sign in, it should load all the existing reactions correctly.
> [Feature] react with emoji 

- src/components/MessageBubble.tsx
https://www.pivotaltracker.com/story/show/182353014
> Fix warnings on messages that contain links

- src/contexts/ChatContext.tsx
- src/lib/matrix.ts
- src/lib/matrixHooks.ts
- src/screens/Chat/NewChat.tsx
- src/screens/Chat/index.tsx
- src/screens/Login.tsx
[#182350580](https://www.pivotaltracker.com/story/show/182350580)
Create a new chat with the receiving client open. The chat list should be updated with the new chat and you should be able to exchange messages.
> [Feature] update list of chats with invites

- src/components/MessageInput.tsx
- no longer able to send messages with blank content
- whitespace now trimmed
> Trim messages + prevent empty from being sent

- src/components/Chat/ChatListItem.tsx
- src/components/UserList.tsx
- src/screens/Chat/ChatView.tsx
- https://www.pivotaltracker.com/story/show/182326412
- fixed bad behaviors such as: 
> [Fix] Fixed UI to work with long user names

- src/lib/matrixHooks.ts
> Fix messages from new chats not having "confirmed"prop

- src/components/Chat/ChatItem.tsx
- src/contexts/ChatContext.tsx
- src/lib/matrix.ts
- src/lib/matrixHooks.ts
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/MessageMenu.tsx
- src/types/Chat.ts
[#182250298](https://www.pivotaltracker.com/story/show/182250298)
Go to any chat, you'll notice that not all messages are loaded at once, it'll load as you go up in the screen.
> [Feature] lazy load messages

- package.json
- src/components/Chat/ChatItem.tsx
- src/components/MessageBubble.tsx
- src/contexts/ChatContext.tsx
- src/lib/matrix.ts
- src/lib/matrixHooks.ts
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/ForwardMenu.tsx
- src/screens/Chat/MessageMenu.tsx
- src/types/Chat.ts
- yarn.lock
- https://www.pivotaltracker.com/story/show/182350610
> [Fix] 🗡 Receiving own messages through matrix event

- src/components/Chat/ChatListItem.tsx
- src/contexts/ChatContext.tsx
- src/lib/matrix.ts
- src/lib/matrixHooks.ts
- src/screens/Chat/MessageMenu.tsx
- src/screens/Chat/NewChat.tsx
- src/screens/Login.tsx
- src/types/Chat.ts
https://www.pivotaltracker.com/story/show/182456819
> [Feature] Reaction preview on chat list

- src/components/Chat/ChatListItem.tsx
- src/contexts/ChatContext.tsx
- src/lib/matrix.ts
- src/screens/Chat/ChatList.tsx
- src/screens/Chat/ChatView.tsx
[#182352410](https://www.pivotaltracker.com/story/show/182352410)
> [Feature] unread messages indicator

- src/lib/matrix.ts
> [Fix] scrollback to last unread message

- src/components/Chat/ChatListItem.tsx
- src/components/UserSelector.tsx
- src/contexts/ChatContext.tsx
- src/lib/matrix.ts
- src/lib/matrixHooks.ts
- src/screens/Chat/ChatList.tsx
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/NewChat.tsx
- src/types/Chat.ts
- fix crash when logging in to account that has a new chat room
- rename lastSeen -> lastOpen
- stop showing chats without messages on all lists
> Random improvements

- src/components/Avatar/Avatar.tsx
- src/components/Chat/ChatListItem.tsx
- src/components/UserList.tsx
- src/contexts/ChatContext.tsx
- src/contexts/UserContext.tsx
- src/lib/matrix.ts
- src/lib/matrixHooks.ts
- src/screens/Chat/ChatView.tsx
- src/screens/Chat/NewChat.tsx
- src/types/Chat.ts
> Delete unused isOnline prop

- src/screens/Chat/MessageMenu.tsx
- https://www.pivotaltracker.com/story/show/182005248
- Add "Delete" button to reaction list
> [Feature] Delete button on reaction list
